# Generated by Django 4.0.4 on 2022-06-01 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cat_img', models.ImageField(default='images/floric.jpg', upload_to='images/category/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=5000)),
                ('weight', models.CharField(blank=True, max_length=1000, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=256, null=True)),
                ('brand', models.CharField(blank=True, max_length=256, null=True)),
                ('Model', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.FloatField()),
                ('size', models.CharField(blank=True, max_length=15, null=True)),
                ('posted_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_img1', models.ImageField(default='images/floric.jpg', upload_to='images/products/')),
                ('product_img2', models.ImageField(blank=True, default='images/floric.jpg', null=True, upload_to='images/products/')),
                ('product_img3', models.ImageField(blank=True, default='images/floric.jpg', null=True, upload_to='images/products/')),
                ('product_img4', models.ImageField(blank=True, default='images/floric.jpg', null=True, upload_to='images/products/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
